//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chesterfieldsDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("HotelInfo")]
    public partial class HotelInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelInfo()
        {
            this.HotelImages = new HashSet<HotelImage>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.RoomBookings = new HashSet<RoomBooking>();
            this.RoomDetails = new HashSet<RoomDetail>();
        }
    
        [Key]
        public int Hotel_Id { get; set; }
        public string Hotel_Name { get; set; }
        public string Hotel_Location { get; set; }
        public string Hotel_Email { get; set; }
        public string Hotel_Contact { get; set; }
        public string Hotel_Address { get; set; }
        public string About_Hotel { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelImage> HotelImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBooking> RoomBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomDetail> RoomDetails { get; set; }
    }
}
