//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chesterfieldsDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("RoomBooking")]
    public partial class RoomBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomBooking()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
        
        [Key]
        public int RoomBookingId { get; set; }
        public string RoomType { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<int> No_of_Guests { get; set; }
        public Nullable<int> No_of_Rooms { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Hotel_Id { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual HotelInfo HotelInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual RoomDetail RoomDetail { get; set; }
    }
}
