//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chesterfieldsDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("RoomDetail")]
    public partial class RoomDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomDetail()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.RoomBookings = new HashSet<RoomBooking>();
            this.RoomImages = new HashSet<RoomImage>();
        }
    
        [Key]
        public int RoomTypeId { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> Number_of_Rooms { get; set; }
        public Nullable<int> Available_Rooms { get; set; }
        public Nullable<int> Floor_No { get; set; }
        public Nullable<int> Occupancy { get; set; }
        public Nullable<double> Price { get; set; }
        public string About_Room { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Hotel_Id { get; set; }
        public string Room_Image_Path { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual HotelInfo HotelInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBooking> RoomBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomImage> RoomImages { get; set; }
    }
}
